### PR TITLE
Skeleton

### PR DESCRIPTION
**Pull request by craigtd**

### CODE REVIEW

**Comment by craigtd** [comment]
My intention was to have a skeleton service set up that could be compiled and used to create a docker image for use in testing out the pipelines etc.

**Comment by greg-gajda** [comment]
Is running **sbt assembly** successful on this?
If that's the case then it's good to go.

**Comment by craigtd** [comment]
@greg-gajda - yep - ran that and it packages target/scala-2.13/generate-pdf.jar successfully. OK to merge?

**Review by greg-gajda — APPROVED** [review]
good to go

**Pull request merged**
