### PR TITLE
HMRC logo in original and compressed format

### PR DESCRIPTION
**Pull request by craigtd**

### CODE REVIEW

**Review by greg-gajda — COMMENTED** [review]
Is it the right place for storing HMRC logo?
Did you consider s3://non-repudiation-resources-assets ?

**Comment by craigtd** [comment]
Both files uploaded to https://s3.console.aws.amazon.com/s3/buckets/non-repudiation-resources-assets?region=eu-west-2&prefix=itext/ @greg-gajda

**Comment by craigtd** [comment]
You want me to close this PR?

**Comment by greg-gajda** [comment]
> You want me to close this PR?

With these files moved to s3 it's probably fine to close it, unless you're convinced to keep them in here as well

**Pull request closed without merging**
